spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: greatyaser09@gmail.com
    password: qjmd cuuo jchs oygw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  docker:
    compose:
      enabled: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
   
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    redis:
      host: redis
      port: 6379



server:
  port: 8085
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always


